### ISSUE TITLE
Multiple Scopes per App

### ISSUE THREAD

**Issue by romainmenke** [getconversio/go-shopify#40]
Is it possible to request multiple scopes per request? Seems like it is only possible to request one.

```go
type App struct {
	ApiKey      string
	ApiSecret   string
	RedirectUrl string
	Scope       string
	Password    string
}
```

```go
func (app App) AuthorizeUrl(shopName string, state string) string {
	shopUrl, _ := url.Parse(ShopBaseUrl(shopName))
	shopUrl.Path = "/admin/oauth/authorize"
	query := shopUrl.Query()
	query.Set("client_id", app.ApiKey)
	query.Set("redirect_uri", app.RedirectUrl)
	query.Set("scope", app.Scope)
	query.Set("state", state)
	shopUrl.RawQuery = query.Encode()
	return shopUrl.String()
}
```

https://github.com/romainmenke/go-shopify/commit/2edf7a887a7cf7da9892380099c5d35c083d3da1

This demonstrates how it could be added in a non breaking way.

**Comment by dlebech** [comment]
@romainmenke Thanks for the suggestion. You can use a comma-separated list of scopes for the `Scope` parameter, e.g. `read_products,read_orders,read_customers`. That's how we do it in our projects. I added an extra scope to the [example in the README](https://github.com/getconversio/go-shopify/blob/master/README.md#oauth) so this is more clear.

As a bit of background, I originally implemented it like this because we store the scope in a single environment variable (`SHOPIFY_SCOPE=read_products,read_orders,read_customers`), so it was easy to just have a single string.

**Comment by romainmenke** [comment]
@dlebech Thanks for clearing that up! Works for us.

**Comment by dlebech** [comment]
Cool thanks! :beers:
