### ISSUE TITLE
Customer Address

### ISSUE THREAD

**Issue by sudomake** [getconversio/go-shopify#50]
Looking at the docs for a [Customer Address](https://help.shopify.com/api/reference/customeraddress), it looks very similar to a Billing Address and Shipping Address for an [Order](https://help.shopify.com/api/reference/order#Order properties)

The differences are:

- A Customer address has an ID
- Order addresses have latitude and longitude

Would you like to keep the types separate or combine these into one type?

**Comment by dlebech** [comment]
I would probably personally lean towards re-using the existing `Address` struct, simply because that would potentially make it easier to use the same address instance on a order, customer and/or customeraddress resource, if needed. For example, say I have a customer address for John Doe, and I want to create an order with that address, I would be able to use this address directly instead of having to copy each field.

By the way, the existing address struct also [already has an ID field](https://github.com/getconversio/go-shopify/blob/fe2815a72a86bab94846fa0bcff8c07ddf6bdb2f/order.go#L86) so it should be good to go.

If you want a different struct for the customer address resource, you could embed the current `Address` struct inside a `CustomerAddress` struct, like so:
```
type CustomerAddress struct {
	Address
}
```
In this case, an instance of `CustomerAddress` has direct access to all the same fields as the address. [Example playground](https://play.golang.org/p/HOjN6fNc8z). And I *think* the json decoder also knows how to deal with embedded structs like this, but it would need a test of course :)

**Comment by andrewhoff** [comment]
This issue was moved to bold-commerce/go-shopify#10
