### ISSUE TITLE
style: initialisms do not follow standard go style guidlines

### ISSUE THREAD

**Issue by apkrieg** [getconversio/go-shopify#78]
```go
app := goshopify.App{
    ApiKey: "abcd",
    ApiSecret: "efgh",
    RedirectUrl: "https://example.com/shopify/callback",
    Scope: "read_products,read_orders",
}
```
should look like:
```go
app := goshopify.App{
    APIKey: "abcd",
    APISecret: "efgh",
    RedirectURL: "https://example.com/shopify/callback",
    Scope: "read_products,read_orders",
}
````

I understand the backwards compatibility thing, but maybe we can start working on version 2.X.X and fix this?

Cites:
https://github.com/golang/lint/blob/master/lint.go#L749

**Comment by dlebech** [comment]
@apkrieg I take the blame for this naming as I was still new to Go when creating the library, sorry :-) Newer code has more proper naming, which results in funny things like having [`Url`](https://github.com/getconversio/go-shopify/blob/fcd37f8f62695de1858b0b4bae1b4553b0333222/oauth.go#L20) and [`URL`](https://github.com/getconversio/go-shopify/blob/fcd37f8f62695de1858b0b4bae1b4553b0333222/oauth.go#L68) naming within the same file.

**Comment by dlebech** [comment]
From a pragmatic point of view, updating the naming would require either just breaking all existing installations (if people are not using vendoring) or starting to use something like `gopkg`, adding a new default branch etc. The first option is not nice, and the second option requires maintaining two versions of the code for at least a little while. I'm not sure it's worth it just for the sake of renaming a few fields, but if there were other breaking changes that the library absolutely needed, then versioning makes more since.

I acknowledge that this is an opinion, but just my two cents on this. I'm curious to hear from other users of the library if proper field naming is important enough to warrant a breaking change.

Thanks for bringing it up!

**Comment by andrewhoff** [comment]
This issue was moved to bold-commerce/go-shopify#8
